### PR TITLE
Add a rakefile

### PR DESCRIPTION
**Pull request by MatMoore**
I thought it was worth adding a rakefile for consistency with other projects.

Running the default task will run all the tests and lint.

### CODE REVIEW

**Comment by MatMoore** [comment]
Currently fails because jenkins lints the Rakefile, which has strange conventions.

I'll raise another PR for puppet.

**Comment by tijmenb** [comment]
On the linting: not sure why the `rescue LoadError` is necessary, and you can/should use new hash syntax to make Rubocop happy.

**Comment by MatMoore** [comment]
It's not really, I just copied and pasted from the rpsec docs: https://www.relishapp.com/rspec/rspec-core/docs/command-line/rake-task

> We recommend you wrap this in a rescue clause so that you can
> use your Rakefile in an environment where RSpec is unavailable
> (for example on a production server).

Will convert to new hash syntax.

**Comment by tijmenb** [comment]
Ah yeah, good point. You can shut up rubocop by adding a comment in between the `rescue` and `end`.

**Comment by MatMoore** [comment]
I've just delinted the whole thing, we don't distinguish environments right now anyway. You win again, rubucop.

**Comment by tijmenb** [comment]
ARCAB.

**Pull request merged**
